import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily } from '../../styles';

const shadow = Platform.select({
  ios: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  android: { elevation: 1 },
});

/** DoHuub Delivery screens — built on the commerce card language (white 12–16px cards on the blue-tinted background). */
export const deliveryStyles = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    ...shadow,
  },
  cardTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text,
    marginBottom: 10,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 12,
  },
  label: {
    fontFamily: fontFamily.medium,
    fontSize: 14,
    color: colors.text,
    marginBottom: 8,
  },
  hint: {
    fontSize: 12,
    lineHeight: 17,
    color: colors.textMuted,
    marginTop: 6,
  },
  muted: {
    fontSize: 13,
    color: colors.textMuted,
    lineHeight: 19,
  },
  bodyText: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
  },
  strong: {
    fontFamily: fontFamily.semiBold,
    color: colors.text,
  },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.white,
  },
  inputMultiline: {
    minHeight: 76,
    textAlignVertical: 'top',
  },
  fieldGap: {
    marginBottom: 14,
  },
  // Address choice chips
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(46, 122, 217, 0.18)',
    backgroundColor: colors.white,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: colors.textAccent,
  },
  chipTextActive: {
    color: colors.white,
  },
  stopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  stopBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopBadgeText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: 13,
  },
  stopBody: {
    flex: 1,
    minWidth: 0,
  },
  stopTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
    color: colors.text,
  },
  stopLine: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
    lineHeight: 18,
  },
  stopConnector: {
    width: 2,
    height: 18,
    marginLeft: 13,
    marginVertical: 4,
    backgroundColor: colors.border,
  },
  selectedAddress: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  // Fare
  fareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  fareCurrency: {
    fontFamily: fontFamily.semiBold,
    fontSize: 18,
    color: colors.textMuted,
  },
  fareInput: {
    flex: 1,
    fontFamily: fontFamily.bold,
    fontSize: 24,
  },
  guide: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    padding: 10,
    borderRadius: 12,
    backgroundColor: colors.infoLight,
  },
  guideText: {
    flex: 1,
    fontSize: 13,
    color: colors.primaryDark,
    lineHeight: 18,
  },
  segment: {
    flexDirection: 'row',
    backgroundColor: colors.muted,
    borderRadius: 12,
    padding: 4,
  },
  segmentItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
  },
  segmentItemActive: {
    backgroundColor: colors.white,
    ...shadow,
  },
  segmentText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
    color: colors.textMuted,
  },
  segmentTextActive: {
    color: colors.primary,
  },
  // Status / banners
  statusPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusPillText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
  },
  banner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 14,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 1,
  },
  bannerTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
  bannerText: {
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  waitingHero: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  pulseOuter: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.infoLight,
    marginBottom: 12,
  },
  pulseInner: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  countdown: {
    fontFamily: fontFamily.bold,
    fontSize: 28,
    color: colors.text,
    marginTop: 4,
  },
  // Offers
  sortRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  offerCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: 'transparent',
    ...shadow,
  },
  offerCardSelected: {
    borderColor: colors.primary,
  },
  offerHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImg: {
    width: 48,
    height: 48,
  },
  avatarInitials: {
    fontFamily: fontFamily.bold,
    fontSize: 16,
    color: colors.primary,
  },
  offerName: {
    fontFamily: fontFamily.semiBold,
    fontSize: 15,
    color: colors.text,
  },
  offerMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
    marginTop: 4,
  },
  offerMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  offerMetaText: {
    fontSize: 12,
    color: colors.textMuted,
  },
  offerPrice: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    color: colors.primary,
  },
  offerKind: {
    fontSize: 11,
    fontFamily: fontFamily.semiBold,
    marginTop: 2,
    textAlign: 'right',
  },
  // Map + rider
  mapWrap: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: colors.muted,
    marginBottom: 12,
  },
  map: {
    width: '100%',
    aspectRatio: 2,
  },
  mapFallback: {
    width: '100%',
    aspectRatio: 2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  mapLegend: {
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.white,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendText: {
    fontSize: 12,
    color: colors.textMuted,
  },
  callBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.success,
  },
  // Timeline
  stepRow: {
    flexDirection: 'row',
    gap: 12,
  },
  stepRail: {
    alignItems: 'center',
    width: 22,
  },
  stepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  stepLine: {
    width: 2,
    flex: 1,
    minHeight: 18,
  },
  stepBody: {
    flex: 1,
    paddingBottom: 14,
  },
  stepLabel: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
  stepTime: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  // Buttons
  dangerLink: {
    alignItems: 'center',
    paddingVertical: 14,
  },
  dangerLinkText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
    color: colors.danger,
  },
  outlineBtn: {
    minHeight: 50,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    backgroundColor: colors.white,
  },
  outlineBtnText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 15,
    color: colors.primary,
  },
  stars: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginVertical: 12,
  },
  testBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.amberBg,
    borderWidth: 1,
    borderColor: colors.amberBorder,
    marginBottom: 12,
  },
  testBadgeText: {
    flex: 1,
    fontSize: 13,
    color: colors.amberText,
    lineHeight: 18,
  },
  // Bottom sheet
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlaySlate,
  },
  sheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 36,
  },
  sheetIntro: {
    marginBottom: 12,
  },
  sheetButton: {
    marginTop: 12,
  },
  // List
  tabRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 4,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(46, 122, 217, 0.12)',
    backgroundColor: colors.white,
  },
  tabActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  tabText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: colors.text,
  },
  tabTextActive: {
    color: colors.white,
  },
  tabCount: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.muted,
  },
  tabCountActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  tabCountText: {
    fontSize: 11,
    fontFamily: fontFamily.bold,
    color: colors.textAccent,
  },
  listCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.white,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    ...shadow,
  },
  listIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 15,
    color: colors.text,
  },
  listMeta: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 3,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: 24,
  },
  emptyTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text,
    marginTop: 12,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 20,
  },
});
