import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily, radius, spacing } from '../../../styles';

export const styles = StyleSheet.create({
  wrap: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: spacing.lg,
    paddingVertical: 8,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(46, 122, 217, 0.08)',
    ...Platform.select({
      ios: {
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 30,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  locationPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: 'rgba(46, 122, 217, 0.1)',
    borderRadius: 14,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    maxWidth: '60%',
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  locationLabel: {
    fontFamily: fontFamily.semiBold,
    fontSize: 15,
    color: colors.text,
    marginHorizontal: spacing.xs,
  },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoMark: {
    width: 34,
    height: 34,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  logoImage: {
    width: 22,
    height: 22,
  },
  brandName: {
    fontFamily: fontFamily.bold,
    fontSize: 20,
    color: colors.text,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: radius.full,
    backgroundColor: colors.danger,
    borderWidth: 1.5,
    borderColor: colors.surface,
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: radius.full,
    backgroundColor: colors.backgroundAlt,
    marginLeft: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholder: {
    borderWidth: 1,
    borderColor: colors.border,
  },
  addressBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.secondarySurface,
    borderRadius: radius.lg,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
  },
  addressIcon: {
    marginTop: 2,
    marginRight: spacing.sm,
  },
  addressText: {
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text,
    lineHeight: 19,
    marginRight: spacing.sm,
  },
  changeText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: colors.primary,
    textDecorationLine: 'underline',
  },
  emptyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  emptyText: {
    flex: 1,
    fontFamily: fontFamily.medium,
    fontSize: 13,
    lineHeight: 18,
    color: '#92400E',
    marginHorizontal: spacing.sm,
  },
  addText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: '#B45309',
    textDecorationLine: 'underline',
  },
});
