import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily, radius, spacing } from '../../styles';

const TEAL = '#14B8A6';

// Prototype .shadow-card: a soft lift on every white tile.
const cardShadow = Platform.select({
  ios: {
    shadowColor: '#0B2545',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
  },
  android: { elevation: 1 },
});

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  fill: {
    flex: 1,
  },
  // ---- list ----
  filterBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...cardShadow,
  },
  filterCount: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: TEAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterCountText: {
    fontFamily: fontFamily.medium,
    fontSize: 11,
    color: '#FFFFFF',
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm + 4,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    height: 52,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(45, 122, 217, 0.15)',
  },
  searchInput: {
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text,
    paddingVertical: 0,
  },
  listContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl,
    gap: spacing.md,
  },
  count: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: 'rgba(45, 122, 217, 0.15)',
    overflow: 'hidden',
  },
  imageWrap: {
    position: 'relative',
    height: 192,
    backgroundColor: colors.muted,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  imageEmpty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  poweredBadge: {
    position: 'absolute',
    top: spacing.sm + 4,
    right: spacing.sm + 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radius.full,
    overflow: 'hidden',
  },
  heartTopLeft: {
    left: spacing.sm + 4,
    right: 'auto',
  },
  poweredBadgeText: {
    fontFamily: fontFamily.medium,
    fontSize: 12,
    color: '#FFFFFF',
  },
  cardBody: {
    padding: spacing.md,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  name: {
    fontFamily: fontFamily.medium,
    fontSize: 16,
    color: colors.text,
    marginBottom: 4,
  },
  rating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingValue: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text,
  },
  reviews: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
  },
  location: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.sm + 4,
  },
  meta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
  },
  price: {
    fontFamily: fontFamily.medium,
    fontSize: 18,
    color: TEAL,
  },
  priceUnit: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  sheet: {
    maxHeight: '80%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  sheetTitle: {
    fontFamily: fontFamily.medium,
    fontSize: 18,
    color: colors.text,
  },
  sheetClose: {
    padding: spacing.sm,
    borderRadius: radius.lg,
  },
  sheetBody: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  sheetLabel: {
    fontFamily: fontFamily.medium,
    fontSize: 16,
    color: colors.text,
    marginBottom: spacing.sm + 4,
  },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.muted,
    overflow: 'hidden',
  },
  chipActive: {
    backgroundColor: 'transparent',
  },
  chipText: {
    fontFamily: fontFamily.medium,
    fontSize: 14,
    color: colors.text,
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  clearBtn: {
    paddingVertical: spacing.sm + 4,
    borderRadius: radius.lg,
    borderWidth: 2,
    borderColor: 'rgba(45, 122, 217, 0.15)',
    alignItems: 'center',
  },
  clearText: {
    fontFamily: fontFamily.medium,
    fontSize: 16,
    color: colors.text,
  },
  applyBtn: {
    height: 56,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  applyText: {
    fontFamily: fontFamily.medium,
    fontSize: 16,
    color: '#FFFFFF',
  },

  // ---- detail ----
  gradientClip: {
    overflow: 'hidden',
  },
  detailScroll: {
    paddingBottom: spacing.xl,
  },
  hero: {
    height: 256,
    backgroundColor: colors.muted,
  },
  heroImage: {
    height: 256,
  },
  heroBadge: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radius.full,
  },
  heroBadgeText: {
    fontFamily: fontFamily.medium,
    fontSize: 14,
    color: '#FFFFFF',
  },
  dots: {
    position: 'absolute',
    bottom: spacing.md,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  dotActive: {
    backgroundColor: '#FFFFFF',
    transform: [{ scale: 1.2 }],
  },
  detailBody: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    gap: spacing.lg,
  },
  detailTitle: {
    flex: 1,
    fontFamily: fontFamily.medium,
    fontSize: 20,
    color: colors.text,
  },
  detailRatingValue: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text,
  },
  detailReviews: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.textSecondary,
  },
  detailMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  detailLocation: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.textSecondary,
  },
  pointsBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm + 4,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  pointsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pointsTitle: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: 'rgb(180, 83, 9)',
  },
  pointsBody: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    lineHeight: 20,
    color: 'rgb(217, 119, 6)',
    marginTop: 2,
  },
  whiteCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...cardShadow,
  },
  hostCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm + 4,
    padding: spacing.md,
  },
  hostAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hostName: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text,
    textDecorationLine: 'underline',
  },
  hostLine: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 2,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.md,
  },
  statCell: {
    width: '47.5%',
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm + 4,
  },
  statValue: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text,
  },
  statLabel: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
  },
  pricingCard: {
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(20, 184, 166, 0.3)',
    gap: spacing.sm,
  },
  pricingTitle: {
    marginBottom: 4,
  },
  sectionTitle: {
    fontFamily: fontFamily.medium,
    fontSize: 17,
    color: colors.text,
    marginBottom: spacing.sm + 4,
  },
  noMargin: {
    marginBottom: 0,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceLabel: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.textSecondary,
  },
  priceValue: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: TEAL,
  },
  priceValueDark: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text,
  },
  amenityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.sm + 4,
  },
  amenity: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm + 4,
    padding: spacing.sm + 4,
  },
  amenityText: {
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text,
  },
  about: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
  },
  mapBox: {
    height: 160,
    borderRadius: radius.lg,
    backgroundColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapCaption: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.textSecondary,
    marginTop: spacing.sm,
  },
  rules: {
    gap: spacing.sm,
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  ruleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: TEAL,
    marginTop: 9,
  },
  ruleText: {
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
  },
  reviewsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  viewAll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  viewAllText: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: TEAL,
  },
  reviewList: {
    gap: spacing.md,
  },
  reviewCard: {
    padding: spacing.md,
  },
  reviewTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  reviewName: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text,
  },
  reviewDate: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
  },
  reviewStars: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: spacing.sm + 4,
  },
  reviewComment: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  ctaButton: {
    height: 56,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaDisabled: {
    opacity: 0.5,
  },
  ctaText: {
    fontFamily: fontFamily.medium,
    fontSize: 16,
    color: '#FFFFFF',
  },
  empty: {
    alignItems: 'center',
    paddingVertical: spacing.xxl,
    gap: 4,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginTop: spacing.sm,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
  },
  footer: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
});
