import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily } from '../../styles';

/** Shared commerce UI — mirrors PWA mobile food/grocery screens. */
export const commerceStyles = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 32,
  },
  menuSearchWrap: {
    marginHorizontal: 24,
    marginTop: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(46, 122, 217, 0.12)',
  },
  subtitle: {
    fontSize: 16,
    color: colors.textMuted,
    marginBottom: 16,
  },
  choiceCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 24,
    marginBottom: 12,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
    }),
  },
  choiceIconBox: {
    width: 64,
    height: 64,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    overflow: 'hidden',
  },
  choiceIconImg: {
    width: 52,
    height: 52,
  },
  choiceTitle: {
    fontSize: 18,
    fontFamily: fontFamily.semiBold,
    color: colors.text,
    marginBottom: 6,
  },
  choiceDesc: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
  },
  storeCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
    }),
  },
  storeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  storeTile: {
    width: 56,
    height: 56,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  storeTileImg: {
    width: 56,
    height: 56,
    borderRadius: 14,
  },
  storeInfo: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  storeName: {
    fontWeight: '700',
    fontSize: 16,
    color: colors.text,
  },
  dohuubBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  dohuubBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 4,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaValue: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.text,
  },
  rating: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  reviews: {
    fontSize: 13,
    color: colors.textMuted,
  },
  storeLine: {
    color: colors.textMuted,
    marginTop: 4,
    fontSize: 13,
  },
  storeActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  primaryBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  primaryBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  softBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
    backgroundColor: colors.muted,
  },
  softBtnText: {
    color: colors.textAccent,
    fontWeight: '700',
    fontSize: 14,
  },
  outlineBtn: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  outlineBtnText: {
    fontWeight: '700',
    fontSize: 14,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: 24,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginTop: 12,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 20,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    gap: 12,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: { elevation: 1 },
    }),
  },
  pointsBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    width: '100%',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: '#FFF5EC',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.28)',
    marginBottom: 10,
  },
  pointsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.22)',
  },
  pointsText: {
    flex: 1,
    minWidth: 0,
  },
  pointsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#B45309',
  },
  pointsSub: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 17,
    color: '#B45309',
  },
  itemTile: {
    width: 64,
    height: 64,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  itemTileFallback: {
    width: 64,
    height: 64,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(46, 122, 217, 0.08)',
  },
  itemInfo: {
    flex: 1,
    minWidth: 0,
  },
  itemName: {
    fontWeight: '700',
    fontSize: 14,
    color: colors.text,
  },
  itemDesc: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  itemPrice: {
    fontWeight: '700',
    marginTop: 4,
    fontSize: 14,
    color: colors.primary,
  },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.24,
        shadowRadius: 12,
      },
      android: { elevation: 3 },
    }),
  },
  addBtnFill: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(46, 122, 217, 0.14)',
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyBtnPlus: {
    borderWidth: 0,
    backgroundColor: colors.primary,
  },
  qtyBtnFill: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    lineHeight: 18,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  qtyNum: {
    fontWeight: '700',
    minWidth: 16,
    textAlign: 'center',
    fontSize: 14,
    color: colors.text,
  },
  outLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textFaint,
  },
  cartBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    minHeight: 56,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    backgroundColor: colors.primary,
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.28,
        shadowRadius: 16,
      },
      android: { elevation: 5 },
    }),
  },
  cartBarFill: {
    minHeight: 52,
    paddingHorizontal: 18,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cartBarText: {
    flex: 1,
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
    marginRight: 8,
  },
  cartCheckout: {
    flexShrink: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
  },
  cartCheckoutText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 18,
    includeFontPadding: false,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: { elevation: 1 },
    }),
  },
  cardTitle: {
    fontWeight: '700',
    fontSize: 16,
    color: colors.text,
    marginBottom: 10,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  sectionLabel: {
    fontWeight: '700',
    fontSize: 15,
    color: colors.text,
    marginBottom: 8,
    marginTop: 2,
  },
  deliveryAddressCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  deliveryAddressText: {
    flex: 1,
    minWidth: 0,
  },
  deliveryAddressType: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  deliveryAddressLine: {
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
  },
  addressChoiceList: {
    marginTop: 10,
  },
  addressChoiceText: {
    fontWeight: '600',
    color: colors.text,
  },
  checkoutItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 4,
  },
  checkoutItemImage: {
    width: 58,
    height: 58,
    borderRadius: 12,
  },
  checkoutItemImageFallback: {
    width: 58,
    height: 58,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(46, 122, 217, 0.08)',
  },
  checkoutItemInfo: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  checkoutItemName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  checkoutItemUnit: {
    fontSize: 12,
    color: colors.textMuted,
  },
  checkoutQty: {
    alignSelf: 'flex-start',
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: colors.secondarySurface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkoutQtyText: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textMuted,
  },
  checkoutQtyNum: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  checkoutItemSide: {
    alignItems: 'flex-end',
    gap: 8,
  },
  checkoutItemTotal: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    gap: 12,
  },
  summaryLabel: {
    fontSize: 14,
    color: colors.textMuted,
    flex: 1,
  },
  summaryValue: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '500',
  },
  summaryTotal: {
    marginTop: 4,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.dividerSoft,
  },
  addressRow: {
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
    backgroundColor: colors.white,
  },
  orderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    gap: 12,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: { elevation: 1 },
    }),
  },
  orderIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderBody: {
    flex: 1,
    minWidth: 0,
  },
  orderTitle: {
    fontWeight: '700',
    color: colors.text,
    fontSize: 15,
  },
  orderMeta: {
    color: colors.textMuted,
    marginTop: 4,
    fontSize: 13,
  },
  statusPill: {
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 999,
  },
  statusPillText: {
    fontSize: 12,
    fontWeight: '600',
  },
  chipRow: {
    maxHeight: 48,
    paddingHorizontal: 24,
    marginBottom: 6,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(46, 122, 217, 0.12)',
    backgroundColor: colors.white,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    fontWeight: '600',
    fontSize: 13,
  },
  headerSubtitle: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
  },
  note: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 4,
  },
  removeLink: {
    color: '#dc2626',
    fontSize: 13,
    fontWeight: '600',
  },
  linkBtn: {
    marginTop: 8,
  },
  linkBtnText: {
    color: colors.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  poweredBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    maxWidth: 118,
    backgroundColor: colors.primary,
  },
  poweredBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
  },
  headerCart: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
    }),
  },
  headerCartBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCartBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },
  productCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    gap: 14,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: { elevation: 1 },
    }),
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 14,
  },
  productImageFallback: {
    width: 80,
    height: 80,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(46, 122, 217, 0.08)',
  },
  productBody: {
    flex: 1,
    minWidth: 0,
  },
  productFooter: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
  },
  unitLabel: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textMuted,
  },
  addLabelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.primary,
    flexShrink: 0,
  },
  addLabelBtnFill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  addLabelBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 16,
    includeFontPadding: false,
  },
  confirmSection: {
    marginBottom: 16,
    gap: 10,
  },
  confirmSectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  confirmSectionTitle: {
    fontWeight: '700',
    fontSize: 15,
    color: colors.text,
  },
  paymentMethodCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  paymentMethodIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardPicker: {
    marginTop: 8,
    gap: 8,
  },
});

export const ORDER_STATUS_META: Record<string, { label: string; color: string; bg: string }> = {
  pending_payment: { label: 'awaiting payment', color: '#64748B', bg: '#F1F5F9' },
  placed: { label: 'placed', color: '#1D4AAD', bg: '#DBEAFE' },
  preparing: { label: 'preparing', color: '#1E40AF', bg: '#DBEAFE' },
  out_for_delivery: { label: 'out for delivery', color: '#0F766E', bg: '#CCFBF1' },
  delivered: { label: 'delivered', color: '#1D4AAD', bg: '#DBEAFE' },
  cancelled: { label: 'cancelled', color: '#6B7280', bg: '#F3F4F6' },
};

export const ORDER_STATUS_LABEL: Record<string, string> = {
  pending_payment: 'Awaiting payment',
  placed: 'Placed',
  preparing: 'Preparing',
  out_for_delivery: 'Out for delivery',
  delivered: 'Delivered',
  cancelled: 'Cancelled',
};
