import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily, radius, spacing } from '../../styles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  summaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.lg,
    ...Platform.select({
      ios: {
        shadowColor: colors.text,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  summaryImage: {
    width: 48,
    height: 48,
    borderRadius: radius.sm,
    marginRight: spacing.sm,
  },
  summaryImagePlaceholder: {
    backgroundColor: colors.backgroundAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryInfo: {
    flex: 1,
  },
  summaryName: {
    fontFamily: fontFamily.bold,
    fontSize: 15,
    color: colors.text,
  },
  summaryVendor: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 1,
  },
  summaryPrice: {
    fontFamily: fontFamily.bold,
    fontSize: 13,
    color: colors.primary,
    marginTop: 2,
  },
  label: {
    fontFamily: fontFamily.bold,
    fontSize: 13,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  addAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderStyle: 'dashed',
    marginBottom: spacing.md,
  },
  addAddressLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 13,
    color: colors.primary,
    marginLeft: spacing.xs,
  },
  textArea: {
    height: 90,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text,
    marginBottom: spacing.lg,
  },
  pointsBox: {
    backgroundColor: colors.amberBg,
    borderWidth: 1,
    borderColor: colors.amberBorder,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  pointsBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pointsIconWrap: {
    width: 26,
    height: 26,
    borderRadius: radius.full,
    backgroundColor: colors.warningLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.xs,
  },
  pointsBoxTitle: {
    flex: 1,
    fontFamily: fontFamily.bold,
    fontSize: 13,
    color: colors.amberText,
  },
  pointsBoxValue: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
    color: colors.amberTextLight,
  },
  pointsBoxSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: colors.amberTextMid,
    marginTop: 4,
    marginLeft: 34,
  },
  redeemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  redeemRowActive: {
    borderColor: colors.warning,
    backgroundColor: colors.amberBg,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
    marginTop: 1,
  },
  checkboxChecked: {
    backgroundColor: colors.warning,
    borderColor: colors.warning,
  },
  redeemTextCol: {
    flex: 1,
  },
  redeemTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 13,
    color: colors.text,
  },
  redeemSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 2,
  },
  priceSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  priceSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceSummaryLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 15,
    color: colors.text,
  },
  priceSummaryValue: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    color: colors.text,
  },
  priceSummaryNote: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 4,
  },
  confirmButton: {
    marginBottom: spacing.md,
  },
  errorText: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.danger,
    marginBottom: spacing.sm,
  },
});
